version: '3.8'

services:

  php:
    build: .
    container_name: php-app-8
    working_dir: /var/www/pfa
    volumes:
      - ./pfa:/var/www/pfa
    depends_on:
      - db
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: web-app
    ports:
      - "8000:80"
    volumes:
      - ./pfa:/var/www/pfa
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
    networks:
      - app-network

  db:
    image: mariadb
    container_name: db-app
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pfa
      MYSQL_PASSWORD: pfa
      MYSQL_DATABASE: pfa
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
